notifications:
  email: false

dist: trusty
sudo: required

language: cpp

compiler:
  - gcc

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker run -v $(pwd):/root/hercules --name=hercules_docker -it -d ubuntu:16.04
  - >-
    docker exec --privileged -it hercules_docker bash -c "
    apt-get update -qq;
    apt-get -y install python-software-properties;
    apt-get -y install software-properties-common;
    add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    apt-get update -qq;
    apt-get install -y build-essential python cmake;
    apt-get install -y gcc-6 g++-6;
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 20;
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20;
    update-alternatives --config gcc;
    update-alternatives --config g++;
    "

install:
  - docker exec --privileged -it hercules_docker bash -c "apt-get install -y libxxf86vm-dev libgl1-mesa-dev freeglut3-dev"
  - docker exec -it hercules_docker bash -c "cd /root/hercules && python setup.py"

script: 
- >-
  docker exec -it hercules_docker bash -c "
    cd /root/hercules && \
    mkdir build && \
    cd build && \
    cmake -D HERCULES_BUILD_AS_LIBRARY=1 -D HERCULES_GRAPHICS_BACKEND=noop -D HERCULES_BUILD_TESTS=1 .. && \
    make
  "
- docker exec -it hercules_docker bash -c "cd /root/hercules && cd build && ctest"
