language: cpp

matrix:
  include:
  - os: osx
    osx_image: xcode8
    compiler: clang
  - os: linux
    dist: focal
    sudo: required
    compiler: g++

install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    pip install conan
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update
    
    pip install conan
  fi

script: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir build
    cd build

    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    conan create ../conan/ctpl icebreakersentertainment/stable
    conan create ../conan/entityx icebreakersentertainment/stable
    conan create ../conan/angelscript icebreakersentertainment/stable
    conan create ../conan/freeimage icebreakersentertainment/stable
    conan create ../conan/celero icebreakersentertainment/stable

    conan install ..

    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 ..
    make
    ctest
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    cd /travis
  
    mkdir build
    cd build
    
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    
    conan create ../conan/ctpl icebreakersentertainment/stable
    conan create ../conan/entityx icebreakersentertainment/stable
    conan create ../conan/angelscript icebreakersentertainment/stable
    conan create ../conan/freeimage icebreakersentertainment/stable
    conan create ../conan/celero icebreakersentertainment/stable
    
    conan install ..
    
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 ..
    make
    ctest
  fi
