language: cpp

compiler:
  - gcc

dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-6 g++-6 libstdc++-6-dev cmake
  - sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
  - sudo apt-get install -y python

install:
  - python setup.py

script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - g++ -v
  - gcc -v
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 ..
  - make
  - ctest
