language: cpp

matrix:
  include:
  - os: osx
    osx_image: xcode8
    compiler: clang
  - os: linux
    dist: trusty
    sudo: required
    services: docker
    compiler: g++

before_install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:16.04 tail -f /dev/null
    docker ps
  fi

install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    pip install conan
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker exec -t ubuntu-test bash -c "apt-get -qq update;
    apt-get install -y software-properties-common python-software-properties;
    add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    apt-get -qq update;
    apt-get install -y gcc-6 g++-6 cmake;
    apt-get install -y libgl1-mesa-dev libglu1-mesa-dev"

    docker exec -t ubuntu-test bash -c "apt-get install -y python3"
  fi

script: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir build
    cd build

    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    conan create ../conan/ctpl icebreakersentertainment/stable
    conan create ../conan/entityx icebreakersentertainment/stable
    conan create ../conan/angelscript icebreakersentertainment/stable
    conan create ../conan/freeimage icebreakersentertainment/stable
    conan create ../conan/celero icebreakersentertainment/stable

    conan install ..

    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 ..
    make
    ctest
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker exec -t ubuntu-test bash -c "cd /travis;
    ln -s /usr/bin/gcc-6 /usr/local/bin/gcc &&
    ln -s /usr/bin/g++-6 /usr/local/bin/g++ &&
    export CC=/usr/bin/gcc-6 &&
    export CXX=/usr/bin/g++-6 &&
    g++ -v &&
    gcc -v &&
    mkdir build &&
    cd build &&
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan &&
    conan create ../conan/ctpl icebreakersentertainment/stable &&
    conan create ../conan/entityx icebreakersentertainment/stable &&
    conan create ../conan/angelscript icebreakersentertainment/stable &&
    conan create ../conan/freeimage icebreakersentertainment/stable &&
    conan create ../conan/celero icebreakersentertainment/stable &&
    conan install .. &&
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 .. &&
    make &&
    ctest"
  fi
