language: cpp
compiler:
  - gcc
before_install:
  - if test $CC = gcc; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository -y ppa:george-edison55/precise-backports
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libx11-dev x11proto-core-dev libgl1-mesa-dev libgtkglext1-dev
  - if test $CC = gcc; then sudo apt-get install gcc-6 g++-6; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
  - sudo apt-get install --yes --force-yes cmake cmake-data
install:
  - python setup.py
script: 
- mkdir build && cd build && cmake .. && make
