language: cpp

matrix:
  include:
  - os: osx
    osx_image:
    - xcode10.1
    - xcode11.3
    - xcode12.2
    compiler: clang
  - os: linux
    dist: focal
    sudo: required
    compiler: g++

install: |
  set -e

  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install python
    pip install conan
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update

    sudo apt install -y python3

    sudo apt install -y libgl-dev libglu1-mesa-dev

    pip3 install conan
  fi

script: |
  set -e
  
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir build
    cd build

    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    conan create ../conan/ctpl icebreakersentertainment/stable
    conan create ../conan/entityx icebreakersentertainment/stable
    conan create ../conan/angelscript icebreakersentertainment/stable
    conan create ../conan/freeimage icebreakersentertainment/stable
    conan create ../conan/celero icebreakersentertainment/stable

    conan install ..

    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 ..
    make
    ctest
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    cd /travis

    mkdir build
    cd build

    conan profile new default --detect
    conan profile update settings.compiler.libcxx=libstdc++11 default

    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    conan create ../conan/ctpl icebreakersentertainment/stable
    conan create ../conan/entityx icebreakersentertainment/stable
    conan create ../conan/angelscript icebreakersentertainment/stable
    conan create ../conan/freeimage icebreakersentertainment/stable
    conan create ../conan/celero icebreakersentertainment/stable

    conan install ..

    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 ..
    make
    ctest
  fi
