notifications:
  email: false

dist: trusty
sudo: required

language: cpp

compiler:
  - gcc

services:
  - docker

script:
  - >-
    docker run --privileged -v $(pwd):/root/build ubuntu:16.04 bash -c "
    apt-get update -qq;
    apt-get -y install python-software-properties;
    apt-get -y install software-properties-common;
    add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    apt-get update -qq;
    apt-get install -y build-essential libxxf86vm-dev python;
    apt-get install -y gcc-6 g++-6;
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 20;
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20;
    update-alternatives --config gcc;
    update-alternatives --config g++;
    python setup.py;
    mkdir build;
    cd build;
    cmake ..;
    make;
    "
