branches:
  only:
  - master

clone_depth: 5

version: '{build}'

stack: python 3.9

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:/Python39-x64
      PATH: $(PYTHON)/Scripts/;$(PATH)

install:
  - pip install conan

build_script:
  - sh: cd ${APPVEYOR_BUILD_FOLDER}
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan create ../conan/ctpl icebreakersentertainment/stable
  - conan create ../conan/entityx icebreakersentertainment/stable
  - conan create ../conan/angelscript icebreakersentertainment/stable
  - conan create ../conan/freeimage icebreakersentertainment/stable
  - conan create ../conan/celero icebreakersentertainment/stable
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 ..
  - sh: make
  - cmd: msbuild /p:Configuration=Release ice_engine.sln

test_script:
  - ctest
