image: Visual Studio 2015 CTP 6
build_script:
- cmd: >-
    python setup.py
    
    mkdir build
    
    mkdir build\tests
    
    mkdir build\tests\Release
    
    cd build
    
    cmake -G "Visual Studio 14" -D HERCULES_BUILD_AS_LIBRARY=1 -D HERCULES_GRAPHICS_BACKEND=noop -D HERCULES_BUILD_TESTS=1 ..
    
    msbuild /p:Configuration=Release hercules.sln

test_script:
- cmd: ctest
