image: Visual Studio 2019

branches:
  only:
  - master

clone_depth: 5

version: '{build}'

stack: python 3.9

install:
  - choco install -y python
  - pip install conan

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - conan export ../conan/ctpl icebreakersentertainment/stable
  - conan export ../conan/entityx icebreakersentertainment/stable
  - conan export ../conan/angelscript icebreakersentertainment/stable
  - conan export ../conan/freeimage icebreakersentertainment/stable
  - conan install ..
  - cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICEENGINE_BUILD_BENCHMARKS=1 -DICEENGINE_BUILD_TESTS=1 -DICEENGINE_BUILD_AS_LIBRARY=1 ..
  - msbuild /p:Configuration=Release ice_engine.sln
  - ctest
